# -*- coding: utf-8 -*-
"""Final Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yR7XDo7VpTbY-hshGe8ceHGvoAX8eISs

# **Predicting Hospital Readmission in Diabetic Patients: A Machine Learning Study Using the Diabetes 130-US Hospitals Dataset**

Author: Ushna Khan

# Abstract

Hospital readmissions among diabetic patients pose a significant challenge to healthcare systems, contributing to increased medical costs and poorer patient outcomes. This study utilizes the Diabetes 130-US Hospitals (1999–2008) dataset from the UCI Machine Learning Repository to predict whether a patient will be readmitted after discharge. The dataset includes over 101,000 patient encounters and 47 clinical and demographic attributes covering patient characteristics, admission details, and treatment information.

For the purpose of this study, the target variable was reframed as a binary classification task: readmitted versus not readmitted. After data cleaning and removal of invalid entries, the final dataset contained 67,329 patient encounters, with the majority falling into the “not readmitted” category. A series of machine learning experiments were conducted to identify which demographic, hospital, and treatment-related features are most predictive of readmission risk.

The process involved data cleaning, feature transformation, and evaluation of Logistic Regression and Random Forest performance. Preliminary results suggest that hospital utilization factors—such as medication counts, number of laboratory procedures, and time spent in the hospital—are strong predictors of readmission, while demographic variables contribute only limited predictive power. The study demonstrates how interpretable models can be used to uncover clinical insights into diabetic patient management and readmission risk.

# Introduction
Hospital readmission is a key indicator of healthcare quality and efficiency. For patients with diabetes, readmission rates are particularly high and costly, reflecting complications in treatment and medication adherence. Accurately predicting which diabetic patients are likely to be readmitted after discharge can assist hospitals in allocating resources, improving follow-up care, and reducing preventable readmissions.

The Diabetes 130-US Hospitals for Years 1999–2008 dataset provides a large-scale, real-world record of more than 100,000 hospital encounters across 130 U.S. hospitals. It captures both demographic and clinical aspects of patient care, including diagnoses, medication use, admission type, and length of stay. In the original dataset, encounters are categorized as “no readmission”, “readmitted <30 days”, or “readmitted >30 days.” In this study, the task is reframed as a binary classification problem by grouping all readmission cases into a single readmitted class and contrasting them with the not readmitted class. After clean-up, the final dataset consists of 67,329 encounters.

The principal goal of this investigation is to understand which patient, hospital, and treatment attributes most influence overall readmission risk. Specifically, the project addresses the following research questions:
	1.	Does class balancing (given that non-readmissions outnumber readmissions) improve precision and recall for the minority class?
	2.	Which feature categories—demographic, medication-related, or hospital utilization attributes—contribute most to predictive power?
	3.	Do demographic variables such as sex, age, or race show any evidence of bias in prediction or feature weighting?

By approaching the problem through both statistical and machine learning methods, this project aims not only to achieve strong predictive performance but also to reveal the underlying factors that drive readmission behavior among diabetic patients.

# Motivation

The dataset was originally analyzed by Strack et al., who examined statistical associations between patient characteristics, treatments, and readmission outcomes. Their work highlighted several influential factors such as diagnosis categories and HbA1c testing practices. They also introduced the disease-grouping structure commonly used in later studies. Since then, researchers have applied a wide range of machine learning approaches to the same dataset, from traditional models (Logistic Regression, SVMs, Random Forests) to more recent architectures such as gradient boosting and neural networks. Many studies report improvements through techniques like class balancing, feature selection, or embedding-based representations.

However, much of the existing literature focuses heavily on performance metrics, often using complex models that sacrifice interpretability. Relatively fewer studies investigate how different feature groups contribute to prediction, how class imbalance affects precision and recall, or whether demographic variables behave in ways that could indicate bias.

This project builds on previous research but shifts the focus toward interpretability and clinical relevance. Rather than aiming for state-of-the-art accuracy, the goal is to understand how different categories of features like demographic, clinical, treatment-related, and diagnosis-based, shape the prediction of readmission versus non-readmission. This provides a more transparent and practically useful understanding of readmission risk in diabetic patients.

# Section 1: Data Loading and Preprocessing
"""

# import pdb
# from google.colab import drive
from pathlib import Path
import pandas as pd
import numpy as np
import missingno as msno
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

"""## Data Loading"""

# drive.mount('/content/drive')

# LOADING DATA
# data_file = '/content/drive/My Drive/Colab Notebooks/CSC 321/Diabates Data/diabetic_data.csv'

data_file = Path("../data/diabetic_data.csv")

data = pd.read_csv(data_file)
pre_rows, pre_cols = data.shape

print("This is the Diabetes data set. It has", pre_rows, "instances, and it has", pre_cols, "features.")

no, early, late = data['readmitted'].value_counts()
print("The initial of target values are:\n")
print("NO REDADMISSION:",no)
print("<30 (EARLY):",early)
print(">30 (LATE):",late)

# Convert to binary target
data['readmitted'] = data['readmitted'].apply(lambda x: 0 if x == 'NO' else 1)

print("\nBinary target value counts:\n")
print(data['readmitted'].value_counts())

data.head()

"""#### Handling Missing Values
According to Strack et al. (2014) which is the introductory paper for this dataset on UCI's repository, Table 1 reports that the features weight, payer_code, and medical_specialty contain the largest proportions of missing data, approximately 97%, 52%, and 53%, respectively. These three features are removed entirely from the dataset prior to further analysis.

Moreover, most patients have 'None' for max_glu_serum and A1Cresult because those tests were not routinely performed during hospitalization. Due to the low variance in the feature values, they will also be dropped.

"""

# REMOVING FEATURES
print(f"Dropping columns with high missingness and low variance.")
data = data.drop(columns=['max_glu_serum', 'A1Cresult', 'weight', 'payer_code', 'medical_specialty'],errors='ignore')
post_cols = data.shape[1]
print(f"We now have {post_cols} features")

"""Some remaining attributes may still carry little or no information for predicting readmission. For example, columns where nearly all patients have the same category (e.g., drugs never prescribed).
- Numeric columns: using the standard deviation
- Categorical columns: examining the frequency of the most common value

ADD  extremely rare diabetes drugs
"""

low_var_features = []

num_cols = data.select_dtypes(include=[np.number]).columns
cat_cols = data.select_dtypes(exclude=[np.number]).columns

for col in num_cols:
    if data[col].std() == 0:
        low_var_features.append(col)

for col in cat_cols:
    top_freq = data[col].value_counts(normalize=True, dropna=False).iloc[0]
    if top_freq > 0.90:
        low_var_features.append(col)

print(f"Identified {len(low_var_features)} low-variance features:")
print(low_var_features)

data = data.drop(columns=low_var_features, errors='ignore')
post_cols = data.shape[1]

print(f"\nFinal feature count: {post_cols}")

"""Remaining missing entries were handled by simply removing the small number of incomplete rows to ensure data integrity without significantly affecting sample size."""

# HANDLING REMAINING MISSING VALUES
pre_rows = data.shape[0]
data = data.replace('?', np.nan)
data = data.dropna()
post_rows = data.shape[0]

print(f"Dropped {pre_rows - post_rows} rows "
      f"({(pre_rows - post_rows) / pre_rows * 100:.2f}%) containing missing values.")
print(f"Final dataset shape: {data.shape}")

"""#### Removing Repeated Patient Records
The dataset contains multiple encounters for some patients (indicated by patient_nbr). Including multiple admissions from the same individual could bias the model, since encounters from the same patient are not truly independent and may share similar demographics, diagnoses, or treatment patterns.
Thus, we keep the first recorded encounter for each patient_nbr and remove subsequent duplicates.
"""

pre_rows = data.shape[0]
data = data.sort_values('encounter_id').drop_duplicates(subset='patient_nbr', keep='first')
post_rows = data.shape[0]
print(f"Removed {pre_rows - post_rows} duplicate patient encounters.")
print(f"Final dataset now contains {post_rows} unique patients (one encounter each).")

# Drop patient and encounter identifiers (no predictive value)
data = data.drop(columns=['encounter_id', 'patient_nbr'])
print(f"Identifiers removed. Dataset shape: {data.shape}")

"""## Feature Transformation

#### ID Mapping

The original ID fields (admission_source_id, discharge_disposition_id, admission_type_id) contain many categorical codes (20+ unique values each). To align with Strack et al. (2014) and simplify modeling:
- Admission Source was collapsed into three categories: Emergency Room, Physician/Clinic Referral, and Other.
- Discharge Disposition was collapsed into Discharged to Home and Other.
Encounters resulting in death or hospice discharge were removed to prevent bias in readmission analysis.
- Admission Type was dropped, since its information largely overlaps with Admission Source.
"""

# Admissions source type
def simplify_admission_source(x):
    if x == 7:
        return 'Emergency'
    elif x in [1, 2]:
        return 'Referral'
    else:
        return 'Other'

data['admission'] = data['admission_source_id'].apply(simplify_admission_source)

# Discharge disposition type
def simplify_discharge(x):
    if x == 1:
        return 'Home'
    elif x in [11, 13, 19]:
        return 'Remove'
    else:
        return 'Other'

data['discharge'] = data['discharge_disposition_id'].apply(simplify_discharge)

# Remove hospice and death outcomes
pre_rows = data.shape[0]
data = data[data['discharge'] != 'Remove']
post_rows = data.shape[0]

print(f"Removed {pre_rows - post_rows} terminal/hospice encounters "
      f"({(pre_rows - post_rows) / pre_rows * 100:.2f}% of data).")

data = data.drop(columns=['admission_type_id','discharge_disposition_id','admission_source_id'])

data[['admission','discharge']].head()

# One hot encoding
data = pd.get_dummies(data, columns=['admission', 'discharge'], prefix=['adm', 'disch'],drop_first=True)
data[['adm_Other',	'adm_Referral',	'disch_Other']].head()

print(f"Dataset shape: {data.shape}")

"""#### Consolidating diagnosis codes

The variables diag_1, diag_2, and diag_3, represent primary and secondary diagnosis codes (often ICD-9 or ICD-10). Each of these have hundreds of unique codes, making direct modeling infeasible. To handle this, we can group diagnosis codes into broader diagnostic categories, (Circulatory system diseases, Respiratory system diseases, Diabetes-related conditions, Infectious diseases, Injury, Genitourinary, Neoplasms (cancers), Muscoskeletal, and Other conditions) in accordance to Table 2 of of the research report Strack et al. (2014).
"""

data[['diag_1','diag_2','diag_3']].head()

# Creating categories
def map_icd9_category(code):
    try:
        code_num = float(code)
    # handle E or V codes/ other non-integer codes
    except ValueError:
        return 'Other'

    if 250 <= code_num < 251:
        return 'Diabetes'
    elif (390 <= code_num <= 459) or (code_num == 785):
        return 'Circulatory'
    elif (460 <= code_num <= 519) or (code_num == 786):
        return 'Respiratory'
    elif (520 <= code_num <= 579) or (code_num == 787):
        return 'Digestive'
    elif 800 <= code_num <= 999:
        return 'Injury'
    elif 710 <= code_num <= 739:
        return 'Musculoskeletal'
    elif (580 <= code_num <= 629) or (code_num == 788):
        return 'Genitourinary'
    elif 140 <= code_num <= 239:
        return 'Neoplasms'
    else:
        return 'Other'

# create categorical columns
for col in ['diag_1', 'diag_2', 'diag_3']:
    data[col + '_cat'] = data[col].apply(map_icd9_category)

# drop code columns
data = data.drop(['diag_1', 'diag_2', 'diag_3'], axis=1)

data[['diag_1_cat', 'diag_2_cat', 'diag_3_cat']].head()

# define diagnosis groups
categories = [
    'Circulatory', 'Respiratory', 'Digestive', 'Injury',
    'Musculoskeletal', 'Genitourinary', 'Neoplasms',
    'Diabetes', 'Other'
]

# create a new column for each category
for cat in categories:
    data[f'{cat}'] = (
        (data['diag_1_cat'] == cat) |
        (data['diag_2_cat'] == cat) |
        (data['diag_3_cat'] == cat)
    ).astype(int)

# drop categorical columns
data = data.drop(columns=['diag_1_cat', 'diag_2_cat', 'diag_3_cat'])

data[categories].head()

print(f"Dataset shape: {data.shape}")

"""#### Transforming Binary Categories
Specifically, we transform:
- gender: represents biological sex (male/1 or female/0).
- diabetesMed: indicates whether any diabetic medication was prescribed (yes/1 or no/0).
- change: indicates whether there was a change in diabetic medication during the encounter (change/0 or no change/1).

"""

for feature in ['gender', 'diabetesMed', 'change']:
  sns.countplot(x=feature,hue='readmitted',data=data)
  plt.title(f'{feature} vs readmitted')
  plt.legend(title='Readmitted',labels=['0 (No)', '1 (Yes)'])
  plt.show()

le_gender = preprocessing.LabelEncoder()
le_diabetesMed = preprocessing.LabelEncoder()
le_change = preprocessing.LabelEncoder()

# Encode gender
le_gender.fit(data['gender'])
data['gender'] = le_gender.transform(data['gender'])

# Encode diabetesMed
le_diabetesMed.fit(data['diabetesMed'])
data['diabetesMed'] = le_diabetesMed.transform(data['diabetesMed'])

# Encode change
le_change.fit(data['change'])
data['change'] = le_change.transform(data['change'])

data[['gender', 'diabetesMed', 'change']].head()

"""Remove instances where gender is unknown and is encoded as 2."""

# drop the rows where gender == 2
invalid_rows = data[data['gender'] == 2].shape[0]
print("Rows with invalid gender:", invalid_rows)

data = data[data['gender'] != 2]

"""#### Encoding Prescription Drug Features
The four prescription variables (metformin, glipizide, glyburide, insulin) each describe whether the drug was prescribed and if its dosage changed during the hospital encounter (Values: up, down, steady, and no). To reduce sparsity while retaining key information, each drug was label-encoded according to the following:

- 0, if 'No' (not prescribed)
- 1, if 'Steady' (no dosage change)
- 2, if 'Up' (dosage increased)
- -1, if 'Down' (dosage decreased)
"""

def encode_drug(value):
    if value == "No":
        return 0
    elif value == "Steady":
        return 1
    elif value == "Up":
        return 2
    elif value == "Down":
        return -1

drug_cols = ["metformin", "glipizide", "glyburide", "insulin"]

for col in drug_cols:
    data[col] = data[col].apply(encode_drug)

data[drug_cols].head()

# drug_features = ['metformin', 'glipizide', 'glyburide', 'insulin']

# for drug in drug_features:
#     data[f'{drug}_prescribed'] = np.where(data[drug] != 'no', 1, 0)
#     data[f'{drug}_change'] = np.where(data[drug].isin(['up', 'down']), 1, 0)

# data = data.drop(columns=drug_features)

# print(f"Dataset shape after encoding drug features: {data.shape}\n")
# data.head()

"""#### Encoding Race

The race variable originally contains five categories: Caucasian, AfricanAmerican, Hispanic, Asian, and Other. Due to the small number of instances for the Asian and Hispanic categories, they were combined into Other, resulting in three final race groups: Caucasian, AfricanAmerican, and Other.
"""

sns.countplot(x='race',hue='readmitted',data=data)
plt.title('Race vs Readmission')
plt.legend(title='Readmitted',labels=['0 (No)', '1 (Yes)'])
plt.xticks(rotation=30)
plt.show()

data['race'].value_counts()

data['race'] = data['race'].replace({'Hispanic': 'Other', 'Asian': 'Other'})

data = pd.get_dummies(data, columns=['race'], prefix='race', drop_first=True)

print(f"Dataset shape after encoding race: {data.shape}\n")
data[['race_Caucasian','race_Other']].head()

"""#### Encoding Age

The age variable represents 10-year intervals, such as [0-10), [10-20), up to [90-100). To simplify this feature and make it more clinically meaningful, these intervals were grouped into three broader categories:
- ≤30 years old
- 30–60 years old
- \>60 years old
"""

def simplify_age(age_str):
    # extract lower bound from age group
    lower = int(age_str.strip('[]').split('-')[0])
    if lower < 30:
        return '<30'
    elif 30 <= lower < 60:
        return '30-60'
    else:
        return '>60'

data['age_group'] = data['age'].apply(simplify_age)

# one-hot encode age groups
data = pd.get_dummies(data, columns=['age_group'], prefix='age', drop_first=True)
data = data.drop(columns='age')

print(f"Dataset shape after encoding age: {data.shape}\n")
data[['age_<30','age_>60']].head()

data.head()

"""## Exploratory Data Analysis (EDA):

#### Basic Summary
"""

#dataset overview
print(f"This is our Final Diabates Dataset.\nIt has {data.shape[0]} instances and {data.shape[1]} features.")

# summary statistics

# numeric features only
num_features = [
    'time_in_hospital', 'num_lab_procedures', 'num_procedures',
    'num_medications', 'number_outpatient', 'number_emergency',
    'number_inpatient', 'number_diagnoses'
]
print("\nSummary statistics:")
display(data[num_features].describe().T)

# Normalization
scaled = StandardScaler().fit_transform(data[num_features])
scaledData = pd.DataFrame(scaled, columns=num_features)

scaledData.head()

display(scaledData.describe().T)

"""#### Visualizing Features"""

# Plot
plt.tight_layout()
plt.figure(figsize=(15, 12))

for i, col in enumerate(num_features):
    plt.subplot(3, 3, i + 1)
    sns.histplot(scaledData[col], bins=30, kde=False, color='pink')
    plt.title(col)

plt.tight_layout()
plt.show()

"""The variables number_outpatient, number_emergency, and number_inpatient represent the number of times a patient was seen in these settings during the observation period. Their distributions are extremely right-skewed, with the vast majority of patients having a value of 0

#### Target Distribution
"""

#target distribution
print("Target proportions:\n")
print(data['readmitted'].value_counts(normalize=True),'\n')

"""#### Correlation Matrix"""

# Correlation matrix for numeric features only
numeric_cols = data.select_dtypes(include=['int64', 'float64', 'bool']).columns
mask = np.triu(np.ones_like(data[numeric_cols].corr(), dtype=bool))
plt.figure(figsize=(14,10))
sns.heatmap(data[numeric_cols].corr(), cmap='coolwarm',mask=mask, center=0, vmin=-1, vmax=1)
plt.title("Correlation Matrix of Numeric Features")
plt.show()

"""Overall, the majority of correlations are very weak, with most values falling between -0.2 and +0.2. There is a small cluster of modest relationsips in ime in hospital, number of lab procedures, number of medications, number of inpatient visits, and number of diagnoses. This makes sense intuitively since patients who undergo more hospital services in one category tend to require more services in others. In contrast, demographic variables (gender, race, age group) exhibit almost no correlation with either clinical variables or the readmission outcome.

# Section 2: Model Evalutation and Experiments

## Baseline Model
We establish baseline predictive performance without any balancing or feature manipulation. We evaluate two fundamentally different types of models:
- Logistic Regression: a classifier that assumes a linear relationship between features and readmission risk.
-	Random Forest Classifier: a non-linear, ensemble tree-based model capable of capturing complex interactions between clinical, demographic, and medication features.

To ensure a reliable and unbiased performance estimate, we use stratified 10-fold cross-validation, which preserves the proportion of readmitted vs. not-readmitted cases within each fold. A ZeroR baseline (DummyClassifier) is also included to verify that the predictive models outperform majority-class guessing.
"""

data.head()

from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
import numpy as np

X = data.drop('readmitted', axis=1).values
y = data['readmitted'].values

# STORE METRICS
results = {"LR": {"acc": [], "prec": [], "rec": [], "f1": [], "auc": []},"RF": {"acc": [], "prec": [], "rec": [], "f1": [], "auc": []},"ZeroR": {"acc": []}}

skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

for train_index, test_index in skf.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # SCALE
    scaler = MinMaxScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # ZERO R
    zr = DummyClassifier(strategy="most_frequent")
    zr.fit(X_train_scaled, y_train)
    y_pred_zr = zr.predict(X_test_scaled)
    results["ZeroR"]["acc"].append(accuracy_score(y_test, y_pred_zr))

    # LOGISTIC REGRESSION
    lr = LogisticRegression(solver='liblinear')
    lr.fit(X_train_scaled, y_train)
    y_pred_lr = lr.predict(X_test_scaled)
    y_prob_lr = lr.predict_proba(X_test_scaled)[:, 1]

    results["LR"]["acc"].append(accuracy_score(y_test, y_pred_lr))
    results["LR"]["prec"].append(precision_score(y_test, y_pred_lr))
    results["LR"]["rec"].append(recall_score(y_test, y_pred_lr))
    results["LR"]["f1"].append(f1_score(y_test, y_pred_lr))
    results["LR"]["auc"].append(roc_auc_score(y_test, y_prob_lr))

    # RANDOM FOREST
    rf = RandomForestClassifier(n_estimators=200, random_state=42)
    rf.fit(X_train_scaled, y_train)
    y_pred_rf = rf.predict(X_test_scaled)
    y_prob_rf = rf.predict_proba(X_test_scaled)[:, 1]

    results["RF"]["acc"].append(accuracy_score(y_test, y_pred_rf))
    results["RF"]["prec"].append(precision_score(y_test, y_pred_rf))
    results["RF"]["rec"].append(recall_score(y_test, y_pred_rf))
    results["RF"]["f1"].append(f1_score(y_test, y_pred_rf))
    results["RF"]["auc"].append(roc_auc_score(y_test, y_prob_rf))

# PRINT RESULTS

def summarize(model_name):
    metrics = results[model_name]
    print(f"\n=== {model_name} 10-Fold CV Results ===")
    for m, vals in metrics.items():
        print(f"{m.upper():<6}: Mean={np.mean(vals):.4f}, Std={np.std(vals):.4f}")

summarize("ZeroR")
summarize("LR")
summarize("RF")

"""The ZeroR baseline achieves 58.8% accuracy, which reflects the majority-class proportion. This tells us the dataset is imbalanced, and simply predicting the majority class performs reasonably well.

Both Logistic Regression and Random Forest perform only slightly better than ZeroR in accuracy (61%). This small improvement suggests that the models are having difficulty learning meaningful patterns.

Precision for both models is moderate (0.55–0.59), meaning when the model predicts “readmitted,” it is correct about half the time.
However, recall is very low, especially for Logistic Regression (0.22) and only slightly better for Random Forest (0.33). This means the models miss most of the actual readmitted patients.

F1-scores are low (0.32 for LR, 0.42 for RF) because of poor recall.
AUC scores are around 0.62 for both, indicating only weak discrimination between the two classes.

## Class Balancing
"""

from imblearn.over_sampling import SMOTE

# results dictionary
results_smote = {"LR": {"acc": [], "prec": [], "rec": [], "f1": [], "auc": []},"RF": {"acc": [], "prec": [], "rec": [], "f1": [], "auc": []},"ZeroR": {"acc": []}}

skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
sm = SMOTE(random_state=42)

for train_idx, test_idx in skf.split(X, y):

    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    # scale BEFORE SMOTE
    scaler = MinMaxScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    X_train_bal, y_train_bal = sm.fit_resample(X_train_scaled, y_train)

    # ZERO R BASELINE
    zr = DummyClassifier(strategy="most_frequent")
    zr.fit(X_train_bal, y_train_bal)
    y_pred_zr = zr.predict(X_test_scaled)
    results_smote["ZeroR"]["acc"].append(accuracy_score(y_test, y_pred_zr))

    # LOGISTIC REGRESSION
    lr = LogisticRegression(solver='liblinear')
    lr.fit(X_train_bal, y_train_bal)
    y_pred_lr = lr.predict(X_test_scaled)
    y_prob_lr = lr.predict_proba(X_test_scaled)[:,1]

    results_smote["LR"]["acc"].append(accuracy_score(y_test, y_pred_lr))
    results_smote["LR"]["prec"].append(precision_score(y_test, y_pred_lr))
    results_smote["LR"]["rec"].append(recall_score(y_test, y_pred_lr))
    results_smote["LR"]["f1"].append(f1_score(y_test, y_pred_lr))
    results_smote["LR"]["auc"].append(roc_auc_score(y_test, y_prob_lr))

    # RANDOM FOREST
    rf = RandomForestClassifier(n_estimators=200, random_state=42)
    rf.fit(X_train_bal, y_train_bal)
    y_pred_rf = rf.predict(X_test_scaled)
    y_prob_rf = rf.predict_proba(X_test_scaled)[:,1]

    results_smote["RF"]["acc"].append(accuracy_score(y_test, y_pred_rf))
    results_smote["RF"]["prec"].append(precision_score(y_test, y_pred_rf))
    results_smote["RF"]["rec"].append(recall_score(y_test, y_pred_rf))
    results_smote["RF"]["f1"].append(f1_score(y_test, y_pred_rf))
    results_smote["RF"]["auc"].append(roc_auc_score(y_test, y_prob_rf))

# PRINT SUMMARY
def summarize_sm(model):
    print(f"\n=== {model} (SMOTE 10-Fold CV) ===")
    for metric, vals in results_smote[model].items():
        print(f"{metric.upper():<5} Mean={np.mean(vals):.4f}, Std={np.std(vals):.4f}")

summarize_sm("ZeroR")
summarize_sm("LR")
summarize_sm("RF")

"""Applying SMOTE to balance the target classes had a noticeable impact on model behavior, especially for Logistic Regression. As expected, the ZeroR baseline remained unchanged, since it always predicts the majority class and does not learn from the data.

For Logistic Regression, SMOTE significantly improved the model’s ability to identify positive (readmitted) cases. Recall increased from roughly 0.22 to 0.55, and the F1-score also rose from about 0.32 to 0.53. This indicates that after balancing, the model becomes much better at catching actual readmissions, although it does so at the cost of slightly lower precision. Accuracy dropped slightly, but this is expected with balanced data and is less meaningful than the large improvements in recall and F1.

For Random Forest, the effect of SMOTE was smaller. Recall improved moderately (from 0.33 to 0.38), and F1 increased slightly as well. This suggests that RF already handles class imbalance reasonably well on its own, so oversampling offers a smaller benefit compared to Logistic Regression. Precision and AUC remained relatively stable across both versions of the model.

## Feature Importance
"""

X = pd.DataFrame(X, columns=data.drop(columns=['readmitted']).columns)
y = data['readmitted']

rf = RandomForestClassifier(n_estimators=200, random_state=42)
rf.fit(X, y)
importances = pd.Series(rf.feature_importances_, index=X.columns).sort_values(ascending=False)
print(importances)

"""The Random Forest results show that clinical severity and hospital‐utilization features are the strongest predictors of readmission, while demographics contribute very little.

Top Predictors (Most Important)
- num_lab_procedures, num_medications, time_in_hospital, num_procedures, number_diagnoses
These features all reflect how intensive or complex the hospital stay was. Patients who receive more tests, procedures, medications, or stay longer are more likely to be readmitted.

Moderate Predictors
- Medication features (insulin, metformin, glipizide, glyburide)
- Diagnosis groups (Diabetes, Respiratory, Circulatory, Digestive, etc.)
These provide useful but secondary information related to disease burden and treatment patterns.

Weak Predictors
- Age, gender, race, and other demographics
These have very low importance, suggesting the model does not rely heavily on demographic differences to make predictions. This might be due to imbalance in the data e.g. mostly caucasian patient encounters.

Conclusion: Readmission risk is driven mainly by clinical complexity, not by demographic attributes. This is a good indication that the model is focusing on meaningful medical factors and is unlikely to exhibit strong demographic bias.

## Grouping Features
"""

importances = rf.feature_importances_
feature_importance = pd.Series(importances, index=X.columns)

# Define feature groups
groups = {
    "Demographic": ['gender', 'race_Caucasian', 'race_Other', 'age_<30', 'age_>60'],
    "Medication": ['metformin', 'glipizide', 'glyburide', 'insulin', 'diabetesMed', 'change'],
    "Hospital Info": ['time_in_hospital', 'num_lab_procedures', 'num_procedures',
                      'num_medications', 'number_outpatient', 'number_emergency',
                      'number_inpatient', 'number_diagnoses', 'adm_Other',
                      'adm_Referral', 'disch_Other'],
    "Diagnosis Categories": ['Circulatory','Respiratory','Digestive','Injury',
                             'Musculoskeletal','Genitourinary','Neoplasms',
                             'Diabetes','Other']
}

# Sum importance per group
group_scores = {g: feature_importance[cols].sum() for g, cols in groups.items()}

pd.Series(group_scores).sort_values(ascending=False)

"""The grouped feature importance analysis shows that hospital-related variables (length of stay, number of lab tests, number of procedures, outpatient/emergency counts, etc.) contribute the majority of overall model importance. Diagnosis categories come next with moderate weight, while medication-related features contribute smaller but still meaningful predictive signals. Demographic features contribute the least overall. This suggests that clinical activity and hospital utilization are stronger indicators of readmission risk than demographic characteristics.

## Evaluating Model On Select Features
"""

strong_features = ['num_lab_procedures','num_medications','time_in_hospital','num_procedures','number_diagnoses']
weak_features = ['gender', 'race_Caucasian', 'race_Other', 'age_<30', 'age_>60']
moderate_features = ['insulin','metformin','glipizide','glyburide','Other','number_inpatient','number_outpatient',
                     'number_emergency','adm_Other','adm_Referral','disch_Other','Diabetes',
                     'Respiratory','Digestive','Circulatory','Genitourinary','Musculoskeletal',
                     'Neoplasms','Injury','change','diabetesMed']

# Extract strong and moderate features
X_reduced = data.drop(columns=['readmitted']+ weak_features)
y = data['readmitted']

# Extract strong features only
X_strong = data[strong_features].copy()
y = data['readmitted']

def run_rf_cv(X, y, label=""):
    skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=0)

    accs = []
    precs = []
    recs = []
    f1s = []
    aucs = []

    for train_idx, test_idx in skf.split(X, y):
        X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
        y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

        # Scale
        scaler = MinMaxScaler()
        X_train = scaler.fit_transform(X_train)
        X_test = scaler.transform(X_test)

        # Model
        rf = RandomForestClassifier(n_estimators=200, random_state=0)
        rf.fit(X_train, y_train)
        preds = rf.predict(X_test)
        probs = rf.predict_proba(X_test)[:,1]

        accs.append(accuracy_score(y_test, preds))
        precs.append(precision_score(y_test, preds))
        recs.append(recall_score(y_test, preds))
        f1s.append(f1_score(y_test, preds))
        aucs.append(roc_auc_score(y_test, probs))

    print(f"\n=== Random Forest ({label}) ===")
    print(f"ACC   Mean={np.mean(accs):.4f}, Std={np.std(accs):.4f}")
    print(f"PREC  Mean={np.mean(precs):.4f}, Std={np.std(precs):.4f}")
    print(f"REC   Mean={np.mean(recs):.4f}, Std={np.std(recs):.4f}")
    print(f"F1    Mean={np.mean(f1s):.4f}, Std={np.std(f1s):.4f}")
    print(f"AUC   Mean={np.mean(aucs):.4f}, Std={np.std(aucs):.4f}")

# Run experiments
run_rf_cv(X_reduced, y, "Reduced (No Weak Predictors)")
run_rf_cv(X_strong, y, "Strong Predictors Only")

"""The feature selection experiments explored whether model performance could be improved by removing weaker predictors or by training on only the strongest features.

Removing weak predictors (demographics such as age and race)
The Random Forest trained on the reduced feature set performed almost the same as the full model:
- Accuracy stayed around 0.61
- Precision and F1 were nearly unchanged
- AUC dropped slightly from 0.624 → 0.614
This suggests demographic variables do not strongly influence predictions and their removal does not improve or worsen performance in a meaningful way.

Using only the strongest predictors
When the model was trained using only the top five predictors (lab procedures, medications, time in hospital, procedures, number of diagnoses), performance dropped noticeably:
- Accuracy fell to 0.55
- AUC dropped to 0.53
- All other metrics declined

This means that the model relies on a broader combination of clinical and admission-related features, not just the top-ranked ones. While the strongest variables carry most of the predictive power, the additional moderate predictors still contribute important complementary information.

# Results

The experimental results compare several modelling strategies, including baseline prediction, standard classifiers, SMOTE-balanced models, and feature-selection variants. Logistic Regression and Random Forest both performed slightly better than the ZeroR baseline but achieved only modest accuracy overall. Applying SMOTE improved recall indicating that class imbalance was limiting the models's ability to detect readmitted patients. Feature selection experiments showed that removing weak predictors did not meaningfully improve performance, while restricting the model to only the strongest predictors caused a clear drop in accuracy and AUC. Overall, the results suggest that readmission is influenced by many small signals rather than a small set of dominant predictors.
"""

import pandas as pd

results = {
    "Model": ["ZeroR", "Logistic Regression", "Random Forest", "LR + SMOTE", "RF + SMOTE", "RF (Reduced)", "RF (Strong Only)"],
    "Accuracy": [0.5882, 0.6149, 0.6144, 0.5924, 0.6100, 0.6077, 0.5468],
    "Precision": [None, 0.5867, 0.5527, 0.5047, 0.5376, 0.5372, 0.4411],
    "Recall": [None, 0.2198, 0.3351, 0.5482, 0.3801, 0.3425, 0.3761],
    "F1": [None, 0.3196, 0.4172, 0.5255, 0.4453, 0.4183, 0.4060],
    "AUC": [None, 0.6249, 0.6242, 0.6245, 0.6222, 0.6142, 0.5333]
}

results_df = pd.DataFrame(results)
results_df

plt.figure(figsize=(12,5))
sns.barplot(data=results_df, x="Model", y="F1", palette="viridis")
plt.title("Model Comparison (F1 Score)")
plt.xticks(rotation=45, ha='right')
plt.ylabel("F1 Score")
plt.show()

plt.figure(figsize=(12,5))
sns.barplot(data=results_df, x="Model", y="AUC", palette="magma")
plt.title("Model Comparison (AUC)")
plt.xticks(rotation=45, ha='right')
plt.ylabel("AUC")
plt.show()

"""# Conclusion

This project exlpored readmission prediction in the Diabetes 130-US Hospitals dataset. The models used, Logistic Regressiong and Random Forest, achieved an accuracy of around 61%, only slightly above the baseline. This reflects the inherent dificulty of predicting hospital readmission, which is influenced by many clinical and behavioral factors that were not reported in the dataset.

Feature importance analysis highlighted hospital-related variables (lab procedures, medications, number of diagnoses, and length of stay) as more predictive than demographics, with minimal indication of bias from race or sex. Grouping diagnosis codes into broader disease categories improved interpinterpretabilityrebaility without harming performance, but no feature group had very strong predictive power on its own.

Overall, the results suggest that although machine learning can capture some patterns related to readmission risk, the dataset lacks several key clinical and social determinants needed for high predictive accuracy.

"""